# Generated by Django 2.2.3 on 2019-07-08 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionalemail',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
