# Generated by Django 2.2.3 on 2019-08-16 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        ('email_alerts', '0002_auto_20190708_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='outage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_alert', to='notices.OutageNotice'),
        ),
    ]
