# Generated by Django 2.2.4 on 2019-08-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_alerts', '0003_emailalert_outage'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailalert',
            name='html_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transactionalemail',
            name='html_content',
            field=models.TextField(null=True),
        ),
    ]
