# Generated by Django 2.2.4 on 2019-09-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_alerts', '0006_auto_20190831_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionalemail',
            name='message_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
