# Generated by Django 2.2.3 on 2019-08-16 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutageNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.CharField(max_length=20, unique=True)),
                ('urgency', models.CharField(max_length=20)),
                ('source_url', models.URLField(max_length=256)),
                ('headline', models.CharField(max_length=180)),
                ('details', models.TextField()),
                ('provider', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=25)),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('scraped_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
