# Generated by Django 2.2.4 on 2019-08-27 03:06

import json

from django.db import migrations

from notices.utils import get_datetime_from_text, datetime_as_str


def set_soonest_schedule(apps, test_outage_notice):
    """Performs the same thing as OutageNotice.set_outage_schedules().

    Repeated myself here since using set_outage_schedules() does not 
    seem to work here.
    """
    OutageNotice = apps.get_model('notices', 'OutageNotice')
    for outage in OutageNotice.objects.all():
        if outage.scheduled_for is None:
            current_details = json.loads(outage.details)

            updated_details = []
            soonest_sched = None
            for item in current_details:
                sched = get_datetime_from_text(item.get('when'))
                item['sched'] = sched
                updated_details.append(item)

                if soonest_sched is None or (sched is not None and 
                    sched < soonest_sched):
                    # Assign to temporary variable
                    soonest_sched = sched

            outage.details = json.dumps(updated_details, default=datetime_as_str)
            outage.scheduled_for = soonest_sched
            outage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_outagenotice_scheduled_for'),
    ]

    operations = [
        migrations.RunPython(set_soonest_schedule)
    ]
