# Generated by Django 2.2.4 on 2019-09-05 04:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_auto_20190827_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutageDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=280)),
                ('area', models.TextField()),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc))),
                ('notice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notice_details', to='notices.OutageNotice')),
            ],
        ),
    ]
