# Generated by Django 2.2.4 on 2019-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_outagedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagedetails',
            name='outage_batch',
            field=models.CharField(default='SET 1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outagedetails',
            name='schedule',
            field=models.CharField(max_length=560),
        ),
    ]
