# Generated by Django 2.2.4 on 2019-09-05 04:43

import json
import logging

from django.db import migrations
from django.utils.dateparse import parse_datetime


def set_notice_details(apps, schema_editor):
    """Converts notice details as a separate details object."""
    OutageNotice = apps.get_model('notices', 'OutageNotice')
    OutageDetails = apps.get_model('notices', 'OutageDetails')

    for notice in OutageNotice.objects.all():
        details = json.loads(notice.details)
        for item in details:
            try:
                d = OutageDetails.objects.create(
                    notice=notice,
                    outage_batch=item.get('set_n'),
                    schedule=item.get('when'),
                    area=item.get('where'),
                    reason=item.get('why'),
                    timestamp=parse_datetime(item.get('sched'))
                )
            except Exception as e:
                logging.error(
                    f'Error processing {notice}: {e}'
                )


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_auto_20190905_1239'),
    ]

    operations = [
        migrations.RunPython(set_notice_details)
    ]
