# Generated by Django 2.2.4 on 2019-09-05 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_auto_20190905_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outagenotice',
            name='details',
        ),
        migrations.AlterField(
            model_name='outagenotice',
            name='scheduled_for',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
