# Generated by Django 2.2.4 on 2019-09-05 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_auto_20190905_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outagedetails',
            name='notice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='notices.OutageNotice'),
        ),
    ]
