# Generated by Django 2.2.4 on 2019-09-21 06:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_auto_20190905_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='outagenotice',
            name='scheduled_until',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
