# Generated by Django 2.2.4 on 2019-09-21 07:31

from django.db import migrations
from django.db.models import Max


def set_max_schedule(apps, schema_editor):
    """Gets max schedule from outage details."""
    OutageNotice = apps.get_model('notices.OutageNotice')
    for item in OutageNotice.objects.all():
        if item.details:
            m = item.details.aggregate(farthest_sched=Max('timestamp'))
            item.scheduled_until = m['farthest_sched']
            item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_outagenotice_scheduled_until'),
    ]

    operations = [
        migrations.RunPython(set_max_schedule)
    ]
